version: '3.9'
services:
  backend:
    image: 'project-backend:latest'
    container_name: 'project-backend'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://project_db:5432/project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8090:8090'
    networks:
      - project-network
    depends_on:
      - project_db

  project_db:
    image: 'postgres:15'
    container_name: 'project_db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - project-network

volumes:
  db_data:

networks:
  project-network:
    driver: bridge
